name: mdupdater

on:
    push:
        branches:
            - main

jobs:
    update-md:
        name: Write Markdown
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Run mdupdater
            run: ./.github/mdupdater.sh
      
          - uses: actions/checkout@v2
          - name: Push markdown file to repository
            run: ./.github/commit_push.sh
