name: Docsearch Auto Scraper

on:
    repository_dispatch:
        branches:
            - main

jobs:
    docsearch-scraper:
        name: Run on pipenv
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Initialize python
              uses: actions/setup-python@v2

            - name: Run docsearch-scraper on pipenv shell
              run: ./.github/docsearch_scraper.sh ${{ secrets.DOCSEARCH_APP_ID }} \
                                                  ${{ secrets.DOCSEARCH_API_KEY }} \
                                                  algolia-config.json