name: CI

on:
    push:
        branches:
            - main

jobs:
    update-md:
        name: Write Markdown
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Run mdupdater
            run: ./.github/mdupdater.sh
            
          - name: Push markdown file to repository
            run: ./.github/commit_push.sh

    deploy:
        needs: update-md
        name: Trigger Deployment
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Cloudflare Pages
            uses: Cyb3r-Jak3/actions-cloudflare-pages@v1.0.1
            with:
                account: ${{ secrets.CLOUDFLARE_ID }}
                project: ${{ secrets.CLOUDFLARE_PROJECT }}
                email: ${{ secrets.CLOUDFLARE_EMAIL }}
                global_token: ${{ secrets.CLOUDFLARE_KEY }}

    docsearch-scraper:
        needs: update-md
        name: Docsearch Auto Scraper
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: darrenjennings/algolia-docsearch-action@master
              with:
                  algolia_application_id: ${{ secrets.DOCSEARCH_APP_ID }}
                  algolia_api_key: ${{ secrets.DOCSEARCH_API_KEY }}
                  file: 'algolia-config.json'